Ferme le fichier .xlsx avant de regénérer.

Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\donnees\SAE1.02\Lot2\structuration.py", line 45, in <module>
    workbook_result.save(output_file)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\workbook\workbook.py", line 386, in save
    save_workbook(self, filename)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\writer\excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\zipfile\__init__.py", line 1362, in __init__
    self.fp = io.open(file, filemode)
              ~~~~~~~^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'Erreurs_Separees.xlsx'